# Meilindex sample configuration file.
# Meilindex supports multiple sources for reading mails.
# By default, Meilindex reads this file from /home/user/.meilindex.yaml and creates one if needed.

# File source configuration
file:
  # directory for mailbox files.
  directory: /home/user/.thunderbird/<id>/ImapMail/mailbox
  # mode to use: thunderbird (mailbox files) or Mailspring.
  # For mailspring, provide full path to database file,
  # which is usually /home/user/.config/Mailspring/edgehill.db.
  mode: thunderbird
  # whether to recurse or use single mailbox file
  recursive: "true"

  # batch / page size.
  # Larger batch usually makes indexing faster, but requires more memory. Default is 1000.
  # On modern pc, this could easily be set to 2000 or 5000.
  batch_size: 1000

# Gui tweaks
gui:
  mouse: false

# Imap source
imap:
  folder: INBOX
  password: memailing
  skip_tls_verification: "false"
  tls: "true"
  url: imap.mymail.com:993
  username: me@mymail.com

# Meilisearch
meilisearch:
  api_key: masterKey
  index: mail
  url: http://localhost:7700
